package org.jayjaytee.planetreego.enums;

public enum TOOLS {
    WOOD_SPADE,
    WOOD_AXE,
    WOOD_PICKAXE,
    WOOD_HOE,
    WOOD_SWORD,
    STONE_SPADE,
    STONE_AXE,
    STONE_PICKAXE,
    STONE_HOE,
    STONE_SWORD,
    IRON_SPADE,
    IRON_AXE,
    IRON_PICKAXE,
    IRON_HOE,
    IRON_SWORD,
    GOLD_SPADE,
    GOLD_AXE,
    GOLD_PICKAXE,
    GOLD_HOE,
    GOLD_SWORD,
    DIAMOND_SPADE,
    DIAMOND_AXE,
    DIAMOND_PICKAXE,
    DIAMOND_HOE,
    DIAMOND_SWORD
}
